# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - TZ=Asia/Bangkok
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=no

volumes:
  postgresql_data:
    driver: local
